### ISSUE TITLE
Fatal error with r-magick due to missing .so file

### ISSUE THREAD

**Issue by rdmorin** [conda-forge/r-magick-feedstock#12]
Issue:
After installing r-magick from conda, I get a fatal error due to a missing or un-linked .so file  libMagickCore-7.Q16HDRI.so.6 

```
> library(magick)
Error: package or namespace load failed for ‘magick’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/rmorin/miniconda3/envs/test-magick/lib/R/library/magick/libs/magick.so':
  libMagickCore-7.Q16HDRI.so.6: cannot open shared object file: No such file or directory
```
I reported this issue here and was referred to the maintainers of the conda package. Supposedly the package needs to be re-compiled. 
https://github.com/ropensci/magick/issues/229

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/rmorin/miniconda3/envs/test-magick:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
binutils_impl_linux-64    2.33.1               he1b5a44_7    conda-forge
binutils_linux-64         2.33.1              h9595d00_16    conda-forge
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
certifi                   2019.11.28               py38_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
expat                     2.2.5             he1b5a44_1004    conda-forge
fftw                      3.3.8           nompi_h7f3a6c3_1110    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      2.001                hab24e00_0    conda-forge
font-ttf-source-code-pro  2.030                hab24e00_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
gcc_impl_linux-64         7.3.0                hd420e75_4    conda-forge
gcc_linux-64              7.3.0               h553295d_16    conda-forge
gdk-pixbuf                2.38.2               h3f25603_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.3.0                hdf63c60_4    conda-forge
gfortran_linux-64         7.3.0               h553295d_16    conda-forge
ghostscript               9.22              hf484d3e_1001    conda-forge
giflib                    5.2.1                h516909a_1    conda-forge
glib                      2.58.3          py38h6f030ca_1002    conda-forge
gobject-introspection     1.58.2          py38h5503ade_1002    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
graphviz                  2.42.3               h0511662_0    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
gxx_impl_linux-64         7.3.0                hdf63c60_4    conda-forge
gxx_linux-64              7.3.0               h553295d_16    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
imagemagick               7.0.9_17        pl526ha9fe49d_0    conda-forge
jbig                      2.1               h14c3975_2001    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcroco                  0.6.13               h8d621e5_0    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
librsvg                   2.46.4               h33a7fed_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
make                      4.2.1             h14c3975_2004    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
pcre                      8.43                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.3.1                   py38_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkg-config                0.29.2            h516909a_1006    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.8.1                h357f687_1    conda-forge
r-base                    3.6.2                h3a67422_0    conda-forge
r-curl                    4.3               r36hcdcec82_0    conda-forge
r-magick                  2.2               r36h0357c0b_0    conda-forge
r-magrittr                1.5             r36h6115d3f_1002    conda-forge
r-rcpp                    1.0.3             r36h0357c0b_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
sed                       4.7               h1bed415_1000    conda-forge
setuptools                45.1.0                   py38_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tktable                   2.10                 h555a92e_3    conda-forge
wheel                     0.33.6                   py38_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-for
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
conda info

     active environment : test-magick
    active env location : /home/rmorin/miniconda3/envs/test-magick
            shell level : 2
       user config file : /home/rmorin/.condarc
 populated config files : /home/rmorin/.condarc
          conda version : 4.8.1
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __glibc=2.12
       base environment : /home/rmorin/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/rmorin/miniconda3/pkgs
                          /home/rmorin/.conda/pkgs
       envs directories : /home/rmorin/miniconda3/envs
                          /home/rmorin/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.1 requests/2.22.0 CPython/3.7.3 Linux/2.6.32-573.8.1.el6.x86_64 centos/6.7 glibc/2.12
                UID:GID : 745:100
             netrc file : /home/rmorin/.netrc
           offline mode : False
```
</details>

**Comment by ressy** [comment]
@rdmorin I ran into the same issue except my r-magick was looking for `....so.7` and my imagemagick was slightly older and instead provided `....so.6`.  Until there's a fix with the dependency handling, you could work around it for now by manually getting your r-magick and imagemagick versions from conda to match up.  I went from imagemagick build `7.0.8_68-pl526h51306e4_0` to `7.0.10_0-pl526ha9fe49d_0` with r-magick `2.3-r36h0357c0b_0` (just by pulling in the latest) and that did the trick.

    $ conda list | grep magick
    imagemagick               7.0.10_0        pl526ha9fe49d_0    conda-forge
    r-magick                  2.3               r36h0357c0b_0    conda-forge
    $ R -q -e 'library(magick)'
    > library(magick)
    Linking to ImageMagick 7.0.9.17
    Enabled features: cairo, fontconfig, freetype, fftw, pango, rsvg, webp, x11
    Disabled features: ghostscript, lcms
    >

**Comment by Juke34** [comment]
Same here I tried r-magick 2.5.2 and 2.6.0 with imagemagick `7.0.10_28`  and `7.0.10_60` with the same error.
```
  Erreur : package or namespace load failed for 'magick' in dyn.load(file, DLLpath = DLLpath, ...):
   impossible de charger l'objet partagé '/home/jdainat/.nextflow/conda/rscripts-5c4add8ac5a0bbff5432d9c10a6a5364/lib/R/library/magick/libs/magick.so':
    libMagickCore-7.Q16HDRI.so.7: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
```
 Then I downgraded imagemagick tto `7.0.10_0` and it works

**Comment by dpryan79** [comment]
I'm hoping that this is addressed by #24

**Comment by ressy** [comment]
Yep, works for me with the latest build now.  Thanks!

```
$ conda list | grep magick
imagemagick               7.0.11_14       pl5320hb118871_0    conda-forge
r-magick                  2.7.2             r41h03ef668_1    conda-forge
$ R -q -e 'library(magick)'
> library(magick)
Linking to ImageMagick 7.0.11.14
Enabled features: cairo, fontconfig, freetype, fftw, pango, rsvg, webp, x11
Disabled features: ghostscript, heic, lcms, raw
```

**Comment by dpryan79** [comment]
Let's tentatively close then then and hope that we finally have this fixed. Please feel encouraged to reopen should this pop up again!

**Comment by jchiquet** [comment]
Hi,

Sorry to 'reopen", yet after installing r-magick et imagemagick from conda, I still have this unlinked problem with file libMagickCore-7.Q16HDRI.so.6

```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/share/miniconda/envs/MAP566/lib/R/library/magick/libs/magick.so':
  libMagickCore-7.Q16HDRI.so.9: cannot open shared object file: No such file or directory
Calls: .main ... getNamespace -> loadNamespace -> library.dynam -> dyn.load
```

The version of r-magick and imagemagick installed are 

> imagemagick-7.1.0_19
> r-magick-2.7.2

Don't know if it helps, but it is part of an action that fails, with log found there :

https://github.com/jchiquet/MAP566/runs/4805415089?check_suite_focus=true

Thanks

**Comment by ressy** [comment]
@jchiquet, maybe add a step in your repo's build.yml to tell you all the exact package versions and builds you're getting (`conda list`) and make sure things look right in that.  It seems odd that you would end up with r-magick 2.7.2 when the latest is 2.7.3, so maybe your packages just predate the fix for some reason.  Possibly your R version is dragging in an earlier r-magick version?  If I search for 2.7.2 or greater I see:

```
r-magick                       2.7.2   r36h03ef668_0  conda-forge
r-magick                       2.7.2   r40h03ef668_0  conda-forge
r-magick                       2.7.2   r40h03ef668_1  conda-forge
r-magick                       2.7.2   r41h03ef668_0  conda-forge
r-magick                       2.7.2   r41h03ef668_1  conda-forge
r-magick                       2.7.3   r40h03ef668_0  conda-forge
r-magick                       2.7.3   r41h03ef668_0  conda-forge
```

which looks like r-magick 2.7.2 for R 3.6 (build 0) and R 4.0/4.1 (build 1) and then 2.7.3 for R 4.0/4.1.

If I just ask for r-magick it gets the latest (2.7.3) and everything's fine, but if I ask for these packages with R 3.6, it pulls in r-magick 2.7.2 build 0, which I think doesn't include this fix:

```
$ conda create --name r-magick-test -c conda-forge r=3.6 r-magick imagemagick
...
  r                  conda-forge/noarch::r-3.6-r36_1004
  r-magick           conda-forge/linux-64::r-magick-2.7.2-r36h03ef668_0
  imagemagick        conda-forge/linux-64::imagemagick-7.1.0_19-pl5321hb118871_0
...
```

If that's your issue, I think you could still request a specific imagemagick version to force it work.

I'm not sure how this per-R-version build stuff works for the conda packages, but maybe someone else will chime in.  These build-level differences in conda packages can get really confusing, since you don't always end up with the build you expect and often the build gets forgotten when we focus on package versions.

**Comment by mfansler** [comment]
I am reopening this because while fixing the recipe resolves future builds, one still needs to patch the metadata on the earlier artifacts so future users never encounter this.

**Comment by mfansler** [comment]
Work that needs to be done:

- [ ] inspect all artifacts to see which .so version they each reference
- [ ] identify which versions of `imagemagick` correspond with these
- [ ] submit a repodata patch to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock to constrain coinstallations

**Comment by mfansler** [comment]
Given #50, we've now switched to exact pinning. I don't plan to immediately deal with this, but I've gather the build-time versions that are needed to start to put together a repodata patch ([r-magick__imagemagick__host_requirements.csv](https://github.com/user-attachments/files/29385712/r-magick__imagemagick__host_requirements.csv)). Maybe the next thing needed is a table of which versions of `imagemagick` correspond to various .so.XX versions.
